"""Gemini agro-advisory (PRD F8).

Gemini receives only the structured values the caller supplies and is asked to
explain them. When Gemini is not configured the response is a deterministic
summary explicitly tagged ``source: "deterministic-fallback"`` so the UI can badge
it — it is never passed off as model output.
"""

from fastapi import APIRouter

from app.integrations.gemini import GeminiUnavailable, generate_json
from app.schemas.advisory import AdvisoryRequest

router = APIRouter()

ADVISORY_SCHEMA = {
    "type": "object",
    "properties": {
        "summary": {"type": "string"},
        "observations": {"type": "array", "items": {"type": "string"}},
        "risks": {"type": "array", "items": {"type": "string"}},
        "actions": {"type": "array", "items": {"type": "string"}},
        "irrigation_advice": {"type": "string"},
        "weather_advice": {"type": "string"},
        "monitoring_advice": {"type": "array", "items": {"type": "string"}},
        "uncertainty": {"type": "string"},
    },
    "required": [
        "summary",
        "observations",
        "risks",
        "actions",
        "irrigation_advice",
        "weather_advice",
        "monitoring_advice",
        "uncertainty",
    ],
}


def _build_prompt(payload: AdvisoryRequest) -> str:
    lines = [
        "Structured farm record. Treat every line as the only evidence you have.",
        f"- Location: {payload.location}",
        f"- Crop: {payload.crop}",
        f"- Season: {payload.season}",
        f"- Soil type: {payload.soil_type}",
        f"- Irrigation availability: {payload.irrigation}",
    ]
    if payload.temperature_c is not None:
        lines.append(f"- Current temperature: {payload.temperature_c}°C")
    else:
        lines.append("- Current temperature: NOT AVAILABLE")
    if payload.humidity_pct is not None:
        lines.append(f"- Relative humidity: {payload.humidity_pct}%")
    if payload.rainfall_mm_7d is not None:
        lines.append(f"- Rainfall over the next 7 days: {payload.rainfall_mm_7d}mm")
    if payload.ndvi is not None:
        lines.append(
            f"- Satellite NDVI: {payload.ndvi} ({payload.vegetation_status or 'unclassified'}), "
            f"source {payload.satellite_source or 'unknown'}"
        )
    else:
        lines.append("- Satellite NDVI: NOT AVAILABLE")
    lines.append(f"- Computed farm risk: {payload.risk_level} ({payload.risk_score}/100)")
    if payload.risk_assumptions:
        lines.append("- The risk score relied on these assumptions:")
        lines.extend(f"    * {item}" for item in payload.risk_assumptions)

    lines.append("")
    lines.append(
        "Explain this farm's situation and give concrete, locally sensible actions for "
        "the coming week. Put anything you could not verify into 'uncertainty'. "
        "Do not restate a measurement that is marked NOT AVAILABLE."
    )
    return "\n".join(lines)


def _fallback(payload: AdvisoryRequest) -> dict:
    observations = [f"{payload.crop} on {payload.soil_type} soil in {payload.location}."]
    if payload.temperature_c is not None:
        observations.append(f"Current temperature {payload.temperature_c}°C.")
    if payload.rainfall_mm_7d is not None:
        observations.append(f"{payload.rainfall_mm_7d}mm rain expected over 7 days.")

    return {
        "summary": (
            f"Computed farm risk is {payload.risk_level} ({payload.risk_score}/100). "
            "AI narrative is unavailable, so this is a rule-based summary of the same numbers."
        ),
        "observations": observations,
        "risks": list(payload.risk_assumptions) or ["Risk drivers are shown in the breakdown."],
        "actions": [
            "Review the risk breakdown and address the highest sub-score first.",
            "Record a soil moisture reading to sharpen the water-stress estimate.",
            "Scan a leaf so disease risk uses an observation instead of the baseline.",
        ],
        "irrigation_advice": (
            f"Irrigation is recorded as '{payload.irrigation}'. Schedule against the "
            "rainfall forecast rather than a fixed interval."
        ),
        "weather_advice": "Check the 7-day forecast before any spray or irrigation decision.",
        "monitoring_advice": [
            "Leaf colour and spotting",
            "Soil moisture at root depth",
            "Change in crop condition after rainfall",
        ],
        "uncertainty": (
            "This response was generated by deterministic rules, not by a language model. "
            "It contains no agronomic reasoning beyond the numbers shown."
        ),
        "source": "deterministic-fallback",
        "is_ai_generated": False,
    }


@router.post("")
async def create_advisory(payload: AdvisoryRequest) -> dict:
    try:
        result = await generate_json(
            _build_prompt(payload), ADVISORY_SCHEMA, language=payload.language
        )
    except GeminiUnavailable:
        return _fallback(payload)

    return {
        **result,
        "source": "gemini",
        "is_ai_generated": True,
        "disclaimer": (
            "AI-generated decision support. Verify with your local agricultural "
            "extension officer before acting."
        ),
    }
